import type { NextPage } from 'next';
import Head from 'next/head';
import { onAuthStateChanged, signOut } from 'firebase/auth';
import { auth } from '../firebaseIndex';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();
  // check if user is logged in
  onAuthStateChanged(auth, (user) => {
    if (user) {
      // user is signed in
      const uid = user.uid;
      console.log(uid);
      // ...
    } else {
      // User is signed out
      router.push('/login');
    }
  });

  // log out user
  const logOut = () => {
    signOut(auth)
      .then(() => {
        // Sign-out successful.
      })
      .catch((error) => {
        // An error happened.
        console.log(error);
      });
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Feed</h1>
        <button type='button' onClick={logOut}>
          Log Out
        </button>
      </main>
    </div>
  );
};

export default Home;
